/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Sparkles, RefreshCw, AlertCircle, TrendingUp } from 'lucide-react';
import { Insight, Transaction, Account } from '../types';
import { useState } from 'react';
import { generateFinancialAdvisory } from '../services/geminiService';
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { db } from '../lib/firebase';
import { motion } from 'motion/react';

interface InsightsProps {
  insights: Insight[];
  transactions: Transaction[];
  accounts: Account[];
  userName: string;
  userId: string;
}

export default function Insights({ insights, transactions, accounts, userName, userId }: InsightsProps) {
  const [generating, setGenerating] = useState(false);

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const result = await generateFinancialAdvisory(transactions, accounts, userName);
      await addDoc(collection(db, 'insights'), {
        userId,
        title: result.title,
        content: result.content,
        type: 'advice',
        createdAt: new Date().toISOString()
      });
    } catch (error) {
      console.error("Failed to generate insight", error);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="space-y-8" id="insights-view">
      <header className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-sans font-bold tracking-tight text-neutral-900">AI Financial Insights</h1>
          <p className="text-neutral-500">Personalized wealth management strategies generated by Gemini AI.</p>
        </div>
        <button 
          onClick={handleGenerate}
          disabled={generating}
          className="flex items-center gap-2 bg-neutral-900 text-white px-5 py-2.5 rounded-xl font-medium shadow-lg hover:shadow-xl transition-all disabled:opacity-50 disabled:cursor-not-allowed"
          id="generate-insight-btn"
        >
          {generating ? <RefreshCw size={18} className="animate-spin" /> : <Sparkles size={18} />}
          {generating ? 'Analyzing Data...' : 'Generate New Insight'}
        </button>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {insights.length > 0 ? (
          insights.map((insight, idx) => (
            <motion.div 
              key={insight.id}
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: idx * 0.1 }}
              className="bg-white p-8 rounded-3xl border border-neutral-100 shadow-sm hover:shadow-md transition-all relative overflow-hidden"
            >
              <div className="absolute top-0 right-0 w-32 h-32 bg-neutral-50 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2 opacity-50"></div>
              
              <div className="flex items-center gap-3 mb-6 relative z-10">
                <div className={`p-2 rounded-lg ${
                  insight.type === 'alert' ? 'bg-red-50 text-red-600' : 'bg-neutral-900 text-white'
                }`}>
                  {insight.type === 'alert' ? <AlertCircle size={20} /> : <TrendingUp size={20} />}
                </div>
                <span className="text-xs font-bold uppercase tracking-widest text-neutral-400">
                  {new Date(insight.createdAt).toLocaleDateString()}
                </span>
              </div>

              <h3 className="text-xl font-sans font-bold text-neutral-900 mb-4 relative z-10">{insight.title}</h3>
              <p className="text-neutral-600 leading-relaxed relative z-10">
                {insight.content}
              </p>
            </motion.div>
          ))
        ) : (
          <div className="col-span-full py-20 text-center bg-white rounded-3xl border border-neutral-100 border-dashed">
             <div className="w-16 h-16 bg-neutral-50 rounded-full flex items-center justify-center mx-auto mb-4">
                <Sparkles size={32} className="text-neutral-300" />
             </div>
             <h3 className="font-semibold text-lg text-neutral-900 mb-2">No Insights Yet</h3>
             <p className="text-neutral-500 max-w-xs mx-auto mb-8">
               Generate your first personalized financial insight based on your current accounts and transactions.
             </p>
             <button 
              onClick={handleGenerate}
              className="inline-flex items-center gap-2 text-neutral-900 font-semibold border-b-2 border-neutral-900 pb-1 hover:text-neutral-500 hover:border-neutral-500 transition-all text-sm"
             >
               Analyze My Finances Now
             </button>
          </div>
        )}
      </div>
    </div>
  );
}
